products = [
    {
    '_Id': '1',
    'Name': 'Skybags Bingo 02',
    'image': '/images/1.jpg',
    'Description':'If there’s anything that’ll make you look forward to going out, it’s bingo.Its features are such to make sure that every day is bright and organized.',
    'Brand': 'VIP Industries',
    'Category':'Bagpack',
    'Price': 1200,
    'InStock': 4,
    'rating': 4,
    'TotalReview': 6, 
},
{
    '_Id': '2',
    'Name': 'Skybags Luke 27',
    'image': '/images/2.jpg',
    'Description':'The fun look and vibrant colors used in Luke backpacksmake it stand out from the rest. These bags are a perfect blend ofstyle and functionality which makes them ideal for school.',
    'Brand': 'VIP Industries',
    'Category':'Bagpack',
    'Price': 1150,
    'InStock': 13,
    'rating': 5,
    'TotalReview': 9, 
},
{
    '_Id': '3',
    'Name': 'Skybags Rubik Polyester',
    'image': '/images/3.jpg',
    'Description':'It is made of strong & lightweight polyester shells. Re-engineered lightweight spinner wheels for effortless mobility. Tsa lock ensures security while traveling. Outer Subject matter: Polyester, Casing: Soft. Expander feature for extra packing space, Push Button Trolley, Smooth 4 wheeler Strolly.',
    'Brand': 'VIP Industries',
    'Category':'Strolly',
    'Price': 3900,
    'InStock': 0,
    'rating': 4,
    'TotalReview': 2, 
},
{
    '_Id': '4',
    'Name': 'Skybags Stream Polyester',
    'image': '/images/4.jpg',
    'Description':'This unisex backpack by Skybags is ergonomically designed for all ages, genders and purposes. Made of waterproof and dust-free polyester material, this bag is ideal for use as a school bag, college bag, casual backpack, laptop bag or a work bag.',
    'Brand': 'VIP Industries',
    'Category':'Bagpack',
    'Price': 1700,
    'InStock': 2,
    'rating': 3.5,
    'TotalReview': 1, 
},
{
    '_Id': '5',
    'Name': 'Skybags Beatle Pro',
    'image': '/images/5.jpg',
    'Description':'Offering you nothing but the best, beatle Pro boasts a stylish design with laptop access, 2 compartments and many more functional features. A cut above all professional backpacks',
    'Brand': 'VIP Industries',
    'Category':'Bagpack',
    'Price': 950,
    'InStock': 11,
    'rating': 0.5,
    'TotalReview': 3, 
},
]
